// Mocks generated by Mockito 5.4.6 from annotations
// in graph_go/test/providers/google_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:graph_go/services/google_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GoogleApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleApiService extends _i1.Mock implements _i2.GoogleApiService {
  MockGoogleApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#key),
        ),
      ) as String);

  @override
  _i4.Future<_i2.LatLng?> geocodeAddress(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #geocodeAddress,
          [address],
        ),
        returnValue: _i4.Future<_i2.LatLng?>.value(),
      ) as _i4.Future<_i2.LatLng?>);

  @override
  _i4.Future<Map<String, _i2.LatLng?>> geocodeAddresses(
          List<String>? addresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #geocodeAddresses,
          [addresses],
        ),
        returnValue:
            _i4.Future<Map<String, _i2.LatLng?>>.value(<String, _i2.LatLng?>{}),
      ) as _i4.Future<Map<String, _i2.LatLng?>>);

  @override
  _i4.Future<List<List<int>>> getDistanceMatrix(
    List<_i2.LatLng>? origins, {
    String? travelMode = 'driving',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistanceMatrix,
          [origins],
          {#travelMode: travelMode},
        ),
        returnValue: _i4.Future<List<List<int>>>.value(<List<int>>[]),
      ) as _i4.Future<List<List<int>>>);
}
