// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWSG8ewS_QX2jLfsmO5YsnbKE7HH8HRE',
    appId: '1:627645762372:web:45d648b5ef756be6f2a511',
    messagingSenderId: '627645762372',
    projectId: 'graph-go-bd4f0',
    authDomain: 'graph-go-bd4f0.firebaseapp.com',
    storageBucket: 'graph-go-bd4f0.firebasestorage.app',
    measurementId: 'G-DW8MH83H28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMR4ImXGkhbUuzWebkYOtuCOdRITCnH0I',
    appId: '1:627645762372:android:23f34c4589b71788f2a511',
    messagingSenderId: '627645762372',
    projectId: 'graph-go-bd4f0',
    storageBucket: 'graph-go-bd4f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2mTzC9ArCh672dkMAaWTISnJtZXEkso',
    appId: '1:627645762372:ios:378be489ca7331f7f2a511',
    messagingSenderId: '627645762372',
    projectId: 'graph-go-bd4f0',
    storageBucket: 'graph-go-bd4f0.firebasestorage.app',
    iosClientId: '627645762372-mjpkn58kr2lf5db8o7l0ir0ebcduriij.apps.googleusercontent.com',
    iosBundleId: 'com.example.graphGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2mTzC9ArCh672dkMAaWTISnJtZXEkso',
    appId: '1:627645762372:ios:378be489ca7331f7f2a511',
    messagingSenderId: '627645762372',
    projectId: 'graph-go-bd4f0',
    storageBucket: 'graph-go-bd4f0.firebasestorage.app',
    iosClientId: '627645762372-mjpkn58kr2lf5db8o7l0ir0ebcduriij.apps.googleusercontent.com',
    iosBundleId: 'com.example.graphGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByWSG8ewS_QX2jLfsmO5YsnbKE7HH8HRE',
    appId: '1:627645762372:web:951f0e05232e1b23f2a511',
    messagingSenderId: '627645762372',
    projectId: 'graph-go-bd4f0',
    authDomain: 'graph-go-bd4f0.firebaseapp.com',
    storageBucket: 'graph-go-bd4f0.firebasestorage.app',
    measurementId: 'G-9YWPCDWP20',
  );

}